{
  "hash": "725ec962d8d005a1f0870c257e83dffd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multivariable <br> Regression\"\ndescription: |\n  Discuss how to model multivariable predictors to a single outcome.\nformat:\n  revealjs:\n    width: 1200\n    scrollable: true\n    sc-sb-title: true\n    footer: m201.inqs.info/lectures/8\n    theme: [default, styles.scss]\n    navigation-mode: vertical\n    controls-layout: edges\n    controls-tutorial: true\n    slide-number: true\n    pointer:\n      pointerSize: 32\n    incremental: false \n    chalkboard:\n      theme: whiteboard\n      chalk-width: 4\nknitr:\n  opts_chunk: \n    echo: true\n    eval: true\n    code-fold: true\n    warnings: false\n    comment: \"#>\" \n    \nrevealjs-plugins:\n  - pointer\n  \nfilters:\n  - reveal-header\n  - code-fullscreen\n  - reveal-auto-agenda\n\neditor: source\n---\n## R Packages\n\n\n\n-   rcistats\n-   tidyverse\n\n## Palmer Penguins Data\n\n::: {.columns}\n::: {.column}\n\n### Variables of Interest\n\n- `species`: Penguin species\n- `flipper_len`: Flipper Length in [millimeters](https://en.wikipedia.org/wiki/Millimetre)\n- `body_mass`: Body mass in [grams](https://en.wikipedia.org/wiki/Gram)\n\n:::\n::: {.column}\n![Artwork by @allison_horst](img/penguins.png){fig-alt=\"An image of several penguins in Antartica.\"}\n\n:::\n::: \n\n## Heart Disease Data\n\n::: {.columns}\n::: {.column}\n\n### Variables of Interest\n\n- `thal`: Thallium stress test result\n- `thalach`: Maximum heart rate achieved\n- `disease`: Indicating if they have heart disease\n\n:::\n::: {.column}\n![](img/heart_df.png){fig-alt=\"An image of a graph and a heart.\"}\n:::\n:::\n\n# Visualizations\n\n## Penguins: Body Mass\n\n::: panel-tabset\n\n### Body Mass\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(penguins, aes(body_mass)) +\n  geom_density()\n```\n\n::: {.cell-output-display}\n![](8_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n### Flipper Length\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(penguins, aes(x = flipper_len, y = body_mass)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](8_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n### Species\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(penguins, aes(x = flipper_len, y = body_mass, color = species)) +\n  geom_point() +\n  stat_density_2d(aes(fill = after_stat(level))) +\n  xlim(c(170, 236)) +\n  ylim(c(2500, 6250))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> Warning in stat_density_2d(aes(fill = after_stat(level))): Ignoring unknown\n#> aesthetics: fill\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> Warning: Removed 1 row containing non-finite outside the scale range\n#> (`stat_density2d()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> Warning: Removed 1 row containing missing values or values outside the scale range\n#> (`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](8_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n### Lines\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(penguins, aes(x = flipper_len, y = body_mass, color = species)) +\n  geom_point() +\n  stat_smooth(method = \"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](8_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n:::\n\n\n## Heart Disease\n\n::: panel-tabset\n\n### Disease\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Fit logistic model\n\nggplot(heart_disease, aes(disease)) +\n  geom_bar() +\n  labs(x = NULL, y = NULL)\n```\n\n::: {.cell-output-display}\n![](8_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n### thalach\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Fit logistic model\n\nhdf <- heart_disease\nhdf$plot <- ifelse(hdf$disease==\"yes\", 1, 0)\nggplot(hdf, aes(thalach, plot)) +\n  geom_point(alpha = 0.3) +\n  stat_smooth(method = \"glm\",\n              method.args = list(family = \"binomial\"),\n              se = FALSE) +\n  labs(x = NULL, y = NULL)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](8_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n### thal\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Fit logistic model\n\nggplot(hdf, aes(thalach, plot, col = thal)) +\n  geom_point(alpha = 0.3) +\n  stat_smooth(method = \"glm\",\n              method.args = list(family = \"binomial\"),\n              se = FALSE) +\n  labs(x = NULL, y = NULL)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](8_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n:::\n\n\n# Multivariable Linear Regression\n\n## Multivariable Linear Regression\n\nMultivariable Linear Regression (MLR) is used to model an outcome variable ($Y$) by multiple predictor variables ($X_1, X_2, \\ldots, X_p$).\n\n\n::: fragment\nUsing MLR, you propose that the ouctome variable was constructed from a set of predictors, with their corresponding regression coefficients ($\\beta$), and a bit of error\n:::\n\n\n::: fragment\n$$\nY = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\cdots + \\beta_p X_p + \\varepsilon\n$$\n\n$$\n\\varepsilon \\sim DGP\n$$\n:::\n\n## Model Data\n\n$$\nY = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\cdots + \\beta_p X_p + \\varepsilon\n$$\n\n$$\n\\varepsilon \\sim DGP\n$$\n\n::: fragment\n\n$$\nY_i = \\beta_0 + \\beta_1 X_{i1} + \\beta_2 X_{i2} + \\cdots + \\beta_p X_{ip} + \\varepsilon_i\n$$\n\n$$\n\\varepsilon_i \\sim DGP\n$$\n\n:::\n\n## Unknown Parameters\n\n$$\nY_i = \\beta_0 + \\beta_1 X_{i1} + \\beta_2 X_{i2} + \\cdots + \\beta_p X_{ip} + \\varepsilon_i\n$$\n\n::: fragment\n$$\n\\beta_0, \\beta_1, \\beta_2, \\beta_3, \\ldots, \\beta_p\n$$\n:::\n\n## Estimated Model\n\n$$\nY_i = \\beta_0 + \\beta_1 X_{i1} + \\beta_2 X_{i2} + \\cdots + \\beta_p X_{ip} + \\varepsilon_i\n$$\n\n$$\n\\hat Y_i = \\hat\\beta_0 + \\hat\\beta_1 X_{i1} + \\hat\\beta_2 X_{i2} + \\cdots + \\hat\\beta_p X_{ip} \n$$\n\n## Estimating Prameters\n\n$\\beta_0, \\beta_1, \\beta_2, \\beta_3, \\ldots, \\beta_p$ are estimated by minimizing the following function:\n\n\n$$\n\\sum^n_{i=1} (Y_i-\\hat Y_i)^2\n$$\n\n\n## Fitting a LM in R\n\n```r\nxlm <- lm(Y ~ X1 + X2 + ... + Xp, data = DATA)\nxlm\n```\n\n- `DATA`: Name of the data frame\n- `Y`: Outcome Variable of Interest in the data frame `DATA`\n- `X1`, `X2`, ... , `X_p` : Predictor variables in the data frame `DATA`\n\n\n\n# Multivariable Logistic Regression\n\n## Multivariable Logistic Regression\n\nMultivariable Logistic Regression is used to model a binary outcome variable ($Y$) with multiple predictor variables ($X_1, X_2, \\ldots, X_p$).\n\n\n::: fragment\nUsing Multivariable Logistic Regression, you propose that the ouctome variable was constructed from a set of predictors, with their corresponding regression coefficients ($\\beta_j$), and generated from a Bernoulli model.\n:::\n\n## Logistic Model\n\n$$\nlo(Y=1) = \\beta_0 + \\beta_1X_1 + \\cdots + \\beta_p X_p\n$$\n\n## Regression Coefficients $\\beta$\n\nThe regression coefficients quantify how a specific predictor changes the odds of observing the first category of the outcome ($Y = 1$)\n\n## Estimating $\\beta$\n\nTo obtain the numerical value for $\\beta_j$, denoted as $\\hat \\beta_j$, we will be finding the values of $\\hat \\beta_j$ that maximizes the likelihood function:\n\n$$\nL(\\boldsymbol \\beta) = \\prod_{i=1}^n \\left(\\frac{e^{\\beta_0 + \\beta_1X_1 + \\cdots + \\beta_p X_p}}{1 + e^{\\beta_0 + \\beta_1X_1 + \\cdots + \\beta_p X_p}}\\right)^{Y_i}\\left(\\frac{1}{1 + e^{\\beta_0 + \\beta_1X_1 + \\cdots + \\beta_p X_p}}\\right)^{1-Y_i}\n$$\n\nThe likelihood function can be thought as the probability of observing the entire data set. Therefore, we want to choose the values the $\\beta_0$ and $\\beta_1$ that will result in the highest probability of observing the data.\n\n\n## Estimated Parameters\n\nThe values you obtain ($\\hat \\beta$) tell you the relationship between the a predictor variable and the log odds of observing the first category of the outcome $Y=1$, adjusting for all the other covariates.\n\n::: fragment\nExponentiating the estimate ($e^{\\hat \\beta}$) will give you the relationship between a predictor variable and the odds of observing the first category of the outcome $Y=1$, adjusting for all the other covariates.\n:::\n\n## Interpreting $\\hat \\beta_j$\n\nFor a continuous predictor variable:\n\nAs X increases by 1 unit, the odds of observing the first category ($Y = 1$) increases by a factor of $e^{\\hat\\beta_j}$, adjusting for alll the other predictor variables.\n\nFor a categorical predictor variable (first dummy variable):\n\nThe odds of observing the first category ($Y = 1$) in the indicated category ($D=1$) is $e^{\\hat\\beta_j}$ times higher/lower compared to the reference category ($D=0$), adjusting for alll the other predictor variables.\n\n## Fitting a GLM in R\n\n```r\nxglm <- glm(Y ~ X1 + X2 + ... + Xp, \n           data = DATA,\n           family = binomial)\nxglm\n```\n\n- `DATA`: Name of the data frame\n- `Y`: Outcome Variable of Interest in the data frame `DATA`\n- `X1`, `X2`, ... , `X_p` : Predictor variables in the data frame `DATA`\n\n\n\n# Modelling Body Mass\n\n## Modelling Body Mass\n\n$$\nbody\\_mass = \\beta_0 + \\boldsymbol \\beta_1 (species) + \\beta_2 (flipper\\_len)\n$$\n\n\n## Fitting Model\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nxlm <- lm(body_mass ~ species + flipper_len, \n          data = penguins)\nmodel_info(xlm)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> Outcome Variable: body_mass\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> Numerical Predictors: \n#>    flipper_len\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> Categorical Predictors: \n#>   species: \n#>      Adelie (Reference)  \n#>      Chinstrap  \n#>      Gentoo\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nxlm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> lm(formula = body_mass ~ species + flipper_len, data = penguins)\n#> \n#> Coefficients:\n#>      (Intercept)  speciesChinstrap     speciesGentoo       flipper_len  \n#>         -4013.18           -205.38            284.52             40.61\n```\n\n\n:::\n:::\n\n\n## Estimated Model\n\n$$\nbody\\_mass = -4013.18 -205.38 (Chinstrap)\\\\ + 284.52 (Gentoo) + 40.61 (flipper\\_len)\n$$\n\n\n\n\n## Intepreting $flipper\\_len$ coefficient\n\n$$\nbody\\_mass = -4013.18 -205.38 (Chinstrap)\\\\ + 284.52 (Gentoo) + 40.61 (flipper\\_len)\n$$\n\nAs flipper length increased by 1 unit, body mass increases by an **average** of 40.61, adjusting for penguin species.\n\n\n\n## Intepreting $species$ coefficient\n\n$$\nbody\\_mass = -4013.18 -205.38 (Chinstrap)\\\\ + 284.52 (Gentoo) + 40.61 (flipper\\_len)\n$$\n\n\n::: panel-tabset\n\n### Chinstrap\n\nOn average, the body mass of a Chinstrap species is 205.6 grams lower than an Adelie species, adjusting for flipper length.\n\n### Gentoo\n\nOn average, the body mass of a Gentoo species is 205.6 grams higher than an Adelie species, adjusting for flipper length.\n\n:::\n\n\n# Modeling Heart Disease\n\n## Modelling Heart Disease\n\n$$\nlo(disease) = \\beta_0 + \\boldsymbol \\beta_1 (thal)\\\\ + \\beta_2 (thalach)\n$$\n\n\n## Fitting Model\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nxglm <- lm(disease ~ thal + thalach, \n           data = heart_disease,\n           family = binomial)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> Warning in model.response(mf, \"numeric\"): using type = \"numeric\" with a factor\n#> response will be ignored\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> Warning: In lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) :\n#>  extra argument 'family' will be disregarded\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> Warning in Ops.factor(y, z$residuals): '-' not meaningful for factors\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nmodel_info(xglm)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> Outcome Variable: disease\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> Numerical Predictors: \n#>    thalach\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> Categorical Predictors: \n#>   thal: \n#>      Normal (Reference)  \n#>      Fixed Defect  \n#>      Reversible Defect\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nxglm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> lm(formula = disease ~ thal + thalach, data = heart_disease, \n#>     family = binomial)\n#> \n#> Coefficients:\n#>           (Intercept)       thalFixed Defect  thalReversible Defect  \n#>              2.255233               0.305984               0.459645  \n#>               thalach  \n#>             -0.006621\n```\n\n\n:::\n:::\n\n\n## Estimated Model\n\n$$\nlo(disease) = 2.255 + 0.305 (Fixed) + 0.46 (Reversible)\\\\ - 0.006 (thalach)\n$$\n\n\n\n## Intepreting $thalach$ coefficient\n\n$$\nlo(disease) = 2.255 + 0.305 (Fixed) + 0.46 (Reversible)\\\\ - 0.006 (thalach)\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nexp(-0.006)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.994018\n```\n\n\n:::\n:::\n\n\nAs maximum heart rate achieved increases by 1 unit, the odds of having heart disease decresease by a factor of 0.994, adjusting for thallium stress test results.\n\n## Intepreting $thal$ coefficient\n\n$$\nlo(disease) = 2.255 + 0.305 (Fixed) + 0.46 (Reversible)\\\\ - 0.006 (thalach)\n$$\n\n::: panel-tabset\n\n### Fixed Defect\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nexp(0.305)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 1.356625\n```\n\n\n:::\n:::\n\n\nThe odds of having heart disease is 1.356 times higher in patients with fixed defects thallium stress results than patients with normal thallium stress results, adjusting for maximum heart rate achieved. \n\n### Reversible Defect\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nexp(0.46)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 1.584074\n```\n\n\n:::\n:::\n\n\nThe odds of having heart disease is 1.584 times higher in patients with reversible defects thallium stress results than patients with normal thallium stress results, adjusting for maximum heart rate achieved. \n\n:::\n\n# Model Building\n\n## Model Building\n\nModel Building is the process of obtaining a \"final\" model containing all the necessary predictors, and eliminating any that are not necessary.\n\n## Forward Selection\n\nBegin with the null model ($Y\\sim 1$) and add predictor variables until a final model is chosen.\n\n## Backward Selection\n\nBegin with the full model, and remove predictor variable until the final model is chosen.\n\n## Hybrid Selection\n\nA hybrid approach between the forward and backward building approach.\n\n## About Model Selection\n\nGenerally, it is not a good idea to conduct model selection. The predictor variables in your model should be guided by a literature review that illustrates important predictor variables in a model. Add predictor variables based on consultation with experts and a literature review.\n\n\n",
    "supporting": [
      "8_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}