{
  "hash": "820094af12b0b32bd7e84871761bee8d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: |\n  Simple <br>\n  Linear Regression\ndescription: |\n  Begins the discussion for linear regression.\n\nformat:\n  revealjs:\n    width: 1200\n    scrollable: true\n    sc-sb-title: true\n    footer: m201.inqs.info/lectures/5\n    theme: [default, styles.scss]\n    navigation-mode: vertical\n    controls-layout: edges\n    controls-tutorial: true\n    slide-number: true\n    pointer:\n      pointerSize: 32\n    incremental: false \n    chalkboard:\n      theme: whiteboard\n      chalk-width: 4\nknitr:\n  opts_chunk: \n    echo: true\n    eval: true\n    code-fold: true\n    warnings: false\n    comment: \"#>\" \n    \nrevealjs-plugins:\n  - pointer\n  - verticator\n\nfilters: \n  - reveal-header\n  - code-fullscreen\n  - reveal-auto-agenda\n\neditor: source\n---\n\n## R Packages\n\n\n\n\n-   rcistats\n-   tidyverse\n\n\n## Palmer Penguins Data\n\n::: {.columns}\n::: {.column}\n\n### Variables of Interest\n\n- `flipper_len`: Flipper Length in [millimeters](https://en.wikipedia.org/wiki/Millimetre)\n- `body_mass`: Body mass in [grams](https://en.wikipedia.org/wiki/Gram)\n\n:::\n::: {.column}\n![Artwork by @allison_horst](img/penguins.png){fig-alt=\"An image of several penguins in Antartica.\"}\n\n:::\n::: \n\n\n# Modeling Relationships\n\n## Explaining Variation\n\n::: fragment\nThis is the process where we try to reduce the variation with the use of other variables.\n:::\n\n::: fragment\nCan be thought of as getting it less wrong when taking an educated guess.\n:::\n\n## Modeling Variation\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(penguins, aes(body_mass)) +\n  geom_density() \n```\n\n::: {.cell-output-display}\n![](5_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n\n## Modeling Variation with $\\bar X$\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(penguins, aes(body_mass)) +\n  geom_density() +\n  geom_vline(xintercept = mean(penguins$body_mass))\n```\n\n::: {.cell-output-display}\n![](5_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\n\n## Modeling with a Numerical Variable\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(penguins, aes(x = flipper_len, y = body_mass)) +\n  geom_point() +\n  stat_density_2d(aes(fill = after_stat(level))) +\n  xlim(c(170, 236)) +\n  ylim(c(2500, 6250))\n```\n\n::: {.cell-output-display}\n![](5_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n## Modeling with a Numerical Variable\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(penguins, aes(x = flipper_len, y = body_mass)) +\n  geom_point() +\n  stat_smooth(method = \"lm\", se = F, col = \"red\") +\n  stat_density_2d(aes(fill = after_stat(level))) +\n  xlim(c(170, 236)) +\n  ylim(c(2500, 6250))\n```\n\n::: {.cell-output-display}\n![](5_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n\n\n# A Simple Model\n\n## Generated Model\n\n$$\nY \\sim DGP_1\n$$\n\n## A Simple Model\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(penguins, aes(body_mass)) +\n  geom_density()\n```\n\n::: {.cell-output-display}\n![](5_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n\n## A Simple Model\n\n$$\nY = \\_\\_\\_ + error\n$$\n\n## Notation\n\n$$\nY = \\ \\ \\ \\ \\ \\ \\ \\ \\ + \\varepsilon \n$$\n\n## The Simple Generated Model\n\n$$\nY \\sim \\beta_0 + \\varepsilon\n$$\n\n$$\n\\varepsilon \\sim DGP_2\n$$\n\n::: fragment\n$DGP_2$ is not the same as the $DGP_1$, it is transformed due $\\beta_0$. Consider this the NULL $DGP$.\n:::\n\n## Observing Data\n\n$$\nY = \\beta_0 + \\varepsilon\n$$\n\n## Estimated Line\n\n$$\n\\hat Y=\\hat\\beta_0\n$$\n\n## Notation\n\n::: columns\n::: {.column width=\"50%\"}\n### Observed\n\n$$\nY = \\beta_0 + \\varepsilon\n$$\n:::\n\n::: {.column width=\"50%\"}\n### Estimated\n\n$$\n\\hat Y = \\hat \\beta_0\n$$\n:::\n:::\n\n# Modelling Data\n\n## Indexing Data\n\nThe data in a data set can be indexed by a number.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npenguins[1,-c(1:2)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   bill_len bill_dep flipper_len body_mass  sex year\n#> 1     39.1     18.7         181      3750 male 2007\n```\n\n\n:::\n:::\n\n\n::: fragment\nMaking the variable `body_mass` be represented by $Y$ and `flipper_len` as $X$:\n\n$$\nY_1 = 3750 \\ \\ X_1=181\n$$\n\n:::\n\n## Indexing Data\n\n$$\nY_i, X_i\n$$\n\n## Data\n\nWith the data that we collect from a sample, we hypothesize how the data was generated.\n\n::: fragment\nUsing a simple model:\n\n$$\nY_i = \\beta_0 + \\varepsilon_i\n$$\n\n:::\n\n## Estimated Value\n\n$$\n\\hat Y_i = \\hat \\beta_0\n$$\n\n## Estimation \n\nTo estimate $\\hat \\beta_0$, we minimize the follow function:\n\n$$\n\\sum^n_{i=1} (Y_i-\\hat Y_i)^2\n$$\n\n::: fragment\nThis is known as the sum squared errors, SSE \n:::\n\n\n## Residuals\n\nThe residuals are known as the observed errors from the data in the model:\n\n$$\nr_i = Y_i - \\hat Y_i\n$$\n\n## Estimation in R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlm(Y ~ 1, data = DATA)\n```\n:::\n\n\n\n- `Y`: Name Outcome Variable of Interest in data frame `DATA`\n- `DATA`: Name of the data frame\n\n## Modeling Body Mass in Penguins\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nxlm <- lm(body_mass ~ 1, data = penguins)\nxlm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> lm(formula = body_mass ~ 1, data = penguins)\n#> \n#> Coefficients:\n#> (Intercept)  \n#>        4207\n```\n\n\n:::\n:::\n\n\n::: fragment\n\n$$\n\\hat Y = 4207\n$$\n\n:::\n\n\n## Visualize\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(penguins, aes(body_mass)) +\n  geom_density() +\n  geom_vline(xintercept = 4207)\n```\n\n::: {.cell-output-display}\n![](5_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n\n\n# Linear Model\n\n## Linear Model\n\nThe goal of Statistics is to develop models the have a better explanation of the outcome $Y$.\n\n::: fragment\nIn particularly, reduce the sum of squared errors.\n:::\n\n::: fragment\nBy utilizing a bit more of information, $X$, we can increase the predicting capabilities of the model.\n:::\n\n::: fragment\nThus, the linear model is born.\n:::\n\n## Visualization\n\n::: panel-tabset\n\n### 1-Dimensional\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(penguins, aes(body_mass)) +\n  geom_density()\n```\n\n::: {.cell-output-display}\n![](5_files/figure-revealjs/unnamed-chunk-11-1.png){width=960}\n:::\n:::\n\n\n### 1 $\\rightarrow$ 2\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-dd00900b294d4b6f267f\" style=\"width:960px;height:480px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-dd00900b294d4b6f267f\">{\"x\":{\"visdat\":{\"2ac257ae9caa5\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"2ac257ae9caa5\",\"attrs\":{\"2ac257ae9caa5\":{\"x\":[172,174.45833333333334,176.91666666666666,179.375,181.83333333333334,184.29166666666666,186.75,189.20833333333334,191.66666666666666,194.125,196.58333333333334,199.04166666666666,201.5,203.95833333333334,206.41666666666669,208.875,211.33333333333334,213.79166666666669,216.25,218.70833333333334,221.16666666666669,223.625,226.08333333333334,228.54166666666669,231],\"y\":[2700,2850,3000,3150,3300,3450,3600,3750,3900,4050,4200,4350,4500,4650,4800,4950,5100,5250,5400,5550,5700,5850,6000,6150,6300],\"z\":[[9.3001275924167862e-07,1.6870865703239165e-06,2.6251298434760156e-06,3.5799532157659073e-06,4.3398163810702279e-06,4.7160077026929801e-06,4.6027313880111333e-06,4.014907699678511e-06,3.1100861940930658e-06,2.1494578147287579e-06,1.3702496769536763e-06,8.6204209134446032e-07,5.6593092295469496e-07,3.7659551488753658e-07,2.3071540752796522e-07,1.1905173990009362e-07,4.9071188512829451e-08,1.5875139620175176e-08,4.1807395526537601e-09,1.0605923092147327e-09,3.4898588706295745e-10,1.5110915741552405e-10,6.7785537239312536e-11,2.7961928307829915e-11,1.021806209007994e-11],[1.2307550414665466e-06,2.2314512498464284e-06,3.4795747206341578e-06,4.7719986540930608e-06,5.8378908022984664e-06,6.4165601653892099e-06,6.338014506012077e-06,5.5949123246358107e-06,4.3921354802119588e-06,3.09193589792215e-06,2.0240157695306127e-06,1.3114013722310199e-06,8.7685153554593706e-07,5.8479119677358993e-07,3.5665792004797742e-07,1.8369748710364308e-07,7.6192966598688401e-08,2.5231683320044344e-08,7.1137905160090743e-09,2.1170219257477613e-09,8.4277512869610081e-10,4.0302156091863266e-10,1.8862209038405621e-10,8.0084718701556983e-11,3.0041438621754867e-11],[1.5518700734889793e-06,2.8160419568322001e-06,4.407323891753316e-06,6.0859538438220796e-06,7.5175266696430332e-06,8.355854873744309e-06,8.3497253061546792e-06,7.4589989209119059e-06,5.9383592727713093e-06,4.2634234735461724e-06,2.8675786655804339e-06,1.9112696247102373e-06,1.2996123502761089e-06,8.6887738175592138e-07,5.2847127821903361e-07,2.7249691448031963e-07,1.1436501648048361e-07,3.9243785453642158e-08,1.2145587071554808e-08,4.3045539972189332e-09,2.0004750669393398e-09,1.0260518269611879e-09,4.9713205355755901e-10,2.1690772879724431e-10,8.3518509906761176e-11],[1.8632769900691712e-06,3.3881129100683999e-06,5.3302296567387815e-06,7.420770930736903e-06,9.2617696482829547e-06,1.0411656977796349e-05,1.0524253238521423e-05,9.5167965519162423e-06,7.6909804044574954e-06,5.6380598857751761e-06,3.897704739384992e-06,2.6693664516264247e-06,1.8443480392539034e-06,1.2375597752407838e-06,7.5272865851087066e-07,3.9023441629965357e-07,1.6699075497024972e-07,6.0306132214917709e-08,2.0976844741347667e-08,8.8160171340972085e-09,4.605081910084963e-09,2.4850540871452963e-09,1.2408163330526222e-09,5.5579131028374078e-10,2.1967327552299284e-10],[2.128993183032315e-06,3.8835076001652754e-06,6.1504302948127201e-06,8.64482973999801e-06,1.0911210176933416e-05,1.2409358847255765e-05,1.2691010104754672e-05,1.1623331602433325e-05,9.5455471422553148e-06,7.1532795270906568e-06,5.0838019714220265e-06,3.5742492175902822e-06,2.5092446457499156e-06,1.6935057694436742e-06,1.0341274242435577e-06,5.4219292555477729e-07,2.3894411018230926e-07,9.2427319433180964e-08,3.6709444292905327e-08,1.7923344544855444e-08,1.0190620312098219e-08,5.7165388875977802e-09,2.9334556945177184e-09,1.3478946373480753e-09,5.4692293533727054e-10],[2.3135992039392184e-06,4.2378599378600022e-06,6.7663841348710874e-06,9.6155674738512113e-06,1.2285241372552454e-05,1.4142693042630431e-05,1.4640224350274947e-05,1.359159254336909e-05,1.1357046030253627e-05,8.7101985389275803e-06,6.3649325019593799e-06,4.5916525316740505e-06,3.2780248128174486e-06,2.2324800203713868e-06,1.3758677144798757e-06,7.3513981086886528e-07,3.377058030842352e-07,1.4228956519788849e-07,6.4743733432169363e-08,3.5687821988872824e-08,2.1565628832586059e-08,1.2482789431082889e-08,6.5712339446423502e-09,3.095424358539563e-09,1.2895615658199168e-09],[2.3898569074619881e-06,4.4001765760130193e-06,7.0933267260184332e-06,1.0206330111402794e-05,1.3213590301317134e-05,1.5407151100581445e-05,1.615443292941138e-05,1.5218071443260254e-05,1.2957061740925179e-05,1.0182812919881821e-05,7.6536151391275198e-06,5.6657744786680489e-06,4.1206894718670642e-06,2.8444053197762186e-06,1.7811103919724308e-06,9.7894029702988546e-07,4.7490672866206101e-07,2.2060854781289234e-07,1.1392123225999009e-07,6.8883684519548187e-08,4.3521411844657018e-08,2.5874343501582399e-08,1.3954457573443655e-08,6.734832915870016e-09,2.8808483999487131e-09],[2.3452705284907413e-06,4.344903940818449e-06,7.0825299956905258e-06,1.0333593198031505e-05,1.3570819250387716e-05,1.6039161883294486e-05,1.704785684926248e-05,1.6317258219434228e-05,1.4180016636332218e-05,1.1435768973987405e-05,8.8471244441878123e-06,6.7263262707885937e-06,4.9979230332172361e-06,3.516263667682217e-06,2.2551369418109662e-06,1.2883570104313557e-06,6.6789501248652726e-07,3.4349784797965628e-07,1.9770005070061089e-07,1.2799542126303962e-07,8.3646364919281751e-08,5.0926190398967219e-08,2.8106553311759868e-08,1.3890038660153677e-08,6.100039637689048e-09],[2.1854259239698256e-06,4.0785368698987195e-06,6.7332853369546923e-06,9.9764279877189369e-06,1.3304170048472411e-05,1.5950825478583493e-05,1.7204069988566907e-05,1.6757251179454256e-05,1.4892991035404158e-05,1.2347301463624606e-05,9.8442254574909869e-06,7.6999143666303005e-06,5.8679244372661367e-06,4.2356155396625859e-06,2.8070233676578834e-06,1.6839866462507687e-06,9.4048842473200691e-07,5.3321134576493396e-07,3.3491101799111527e-07,2.2797315147023833e-07,1.530379674297742e-07,9.522231550858498e-08,5.3725390411095442e-08,2.7169399320450727e-08,1.2246793468466623e-08],[1.9328860303617598e-06,3.6384122141923745e-06,6.0935254072791318e-06,9.1819217944629164e-06,1.2446213865336259e-05,1.5150051837069338e-05,1.6601425168004454e-05,1.648692000278122e-05,1.5021362643142177e-05,1.2831374345304503e-05,1.0562735940425936e-05,8.5221719971406874e-06,6.6929019450187741e-06,4.9925480770754197e-06,3.44899743841468e-06,2.1907952673682824e-06,1.3216821032231612e-06,8.1733331838152476e-07,5.4941055963788872e-07,3.882464927951133e-07,2.6655392146133702e-07,1.6924607008952124e-07,9.7520036455333123e-08,5.042978965194787e-08,2.3318689795906656e-08],[1.6219255955010847e-06,3.0839806961175033e-06,5.2487654984797642e-06,8.0546876962652657e-06,1.1108184791137283e-05,1.3739752130520034e-05,1.5318464651518018e-05,1.5546580989452796e-05,1.4562841554136606e-05,1.285253754929251e-05,1.0952429444010373e-05,9.1463042460634541e-06,7.442104084023314e-06,5.7778478906005437e-06,4.1917732344540905e-06,2.8328017571733522e-06,1.8410835219203454e-06,1.2254296457178865e-06,8.6786312168571439e-07,6.313991986793298e-07,4.4213774363531614e-07,2.8613245291722247e-07,1.6820220929839171e-07,8.8870080450106929e-08,4.2117836813255908e-08],[1.2908112682621832e-06,2.4834170830226662e-06,4.3029765359286668e-06,6.7338087936816538e-06,9.4559616310016466e-06,1.1896050214091727e-05,1.3517339143842551e-05,1.4058777261061276e-05,1.3585722251062007e-05,1.2429170160672151e-05,1.0999395641225828e-05,9.5451582794249984e-06,8.0897187690999741e-06,6.5766624664725208e-06,5.0355042786878813e-06,3.6235275879460027e-06,2.5205723999756452e-06,1.78260615063783e-06,1.3151185672445444e-06,9.8001454144031743e-07,6.9878405035664432e-07,4.604620913574641e-07,2.7586205454502628e-07,1.4877054855526885e-07,7.2173243678505275e-08],[9.7405165208785137e-07,1.899789873878446e-06,3.3573991342458152e-06,5.3643643719954571e-06,7.67596531838537e-06,9.8319058321626166e-06,1.1409987236663611e-05,1.2201882957765564e-05,1.2212214786945729e-05,1.1624878439974415e-05,1.0721523507738132e-05,9.7071356675628166e-06,8.6088803680415942e-06,7.3595775064885603e-06,5.9584071692941217e-06,4.5538585671332119e-06,3.3632054434396582e-06,2.5004475543472286e-06,1.907300300099668e-06,1.451605624089458e-06,1.0529568987114249e-06,7.0587687947077358e-07,4.3051857339071664e-07,2.3670397108908494e-07,1.1735243598716818e-07],[6.967855058306223e-07,1.3806651668128154e-06,2.4932756131119674e-06,4.0716301226272685e-06,5.9407123607321597e-06,7.7565775080419524e-06,9.2168606167828669e-06,1.0174433862306812e-05,1.0592441509314639e-05,1.0531968805721811e-05,1.0158467574358539e-05,9.6295193680151075e-06,8.9658543619881536e-06,8.0756084031052848e-06,6.9075680445845987e-06,5.5812437622449248e-06,4.3422902389537687e-06,3.3672348652393007e-06,2.6437135603677566e-06,2.0522302779390602e-06,1.5137534591976317e-06,1.031621389195963e-06,6.3983179037725081e-07,3.5814577669187043e-07,1.8108058846060158e-07],[4.7245131488647956e-07,9.5330380949983646e-07,1.7623161791248863e-06,2.9440782189860919e-06,4.3827069913335176e-06,5.8415894698118598e-06,7.1294079147296592e-06,8.1602503780551027e-06,8.8770568280587076e-06,9.2531073126111722e-06,9.3612419011107848e-06,9.3140594305313047e-06,9.1193186461107862e-06,8.6523503484717671e-06,7.7974190165332594e-06,6.6254349861687245e-06,5.3949446196712431e-06,4.3406057946507933e-06,3.4997073004933462e-06,2.7701791737798098e-06,2.0777073263687415e-06,1.4385612389528927e-06,9.0627550304562213e-07,5.1561248899116023e-07,2.6520769803986671e-07],[3.0362189195117252e-07,6.2544022914885101e-07,1.1856277829614183e-06,2.0276188500244774e-06,3.0815968775293167e-06,4.2005568362027608e-06,5.2850468570040296e-06,6.302883979417189e-06,7.1956084050338128e-06,7.8865748463813084e-06,8.3854909903092366e-06,8.76797504510693e-06,9.0275443725825647e-06,9.0063899124601038e-06,8.5196901069127596e-06,7.5750708805561635e-06,6.4243269958117619e-06,5.3461900841119216e-06,4.4231859810019551e-06,3.5716947628497328e-06,2.7246250768601112e-06,1.9156427544893811e-06,1.2244008096073842e-06,7.0671326255062232e-07,3.6874628760159435e-07],[1.8494371345115316e-07,3.8995451025278261e-07,7.5919228940569485e-07,1.329808839385585e-06,2.0648473286547949e-06,2.8850269740051476e-06,3.7583197361948503e-06,4.6936874458592079e-06,5.6444576879162536e-06,6.5176387165690947e-06,7.2893323114478177e-06,8.0097953669137786e-06,8.6620275761125659e-06,9.0625994793874843e-06,8.9644333114486517e-06,8.3060565090892371e-06,7.3125535093860995e-06,6.2846683546477459e-06,5.3371080975631559e-06,4.4006786637916542e-06,3.4159849377274809e-06,2.4379408778126298e-06,1.5790272036212029e-06,9.227067084454135e-07,4.8687554954869977e-07],[1.0678829061988633e-07,2.3108946987946623e-07,4.6265587185089038e-07,8.3033766157891636e-07,1.3184261043845902e-06,1.8935854653828854e-06,2.5665903380266473e-06,3.3729405442351372e-06,4.2841496191159417e-06,5.2153303038530555e-06,6.1335393179828073e-06,7.0759976795190273e-06,8.0220866874533146e-06,8.7762582729686876e-06,9.0466824629538839e-06,8.7079740089224918e-06,7.9425892642201379e-06,7.0472171452862665e-06,6.1488758561546159e-06,5.1835906193411169e-06,4.0970389933046144e-06,2.967260605827622e-06,1.9451541068673674e-06,1.1481945479597111e-06,6.106718567840748e-07],[5.8460794591845217e-08,1.3017925308063352e-07,2.6828888635408456e-07,4.9348190419339808e-07,8.0222259153579505e-07,1.1885275512285858e-06,1.6850086600767046e-06,2.339948047340856e-06,3.1433757672640817e-06,4.0321021681339948e-06,4.9806675683801057e-06,6.0234081085506764e-06,7.1435596479628303e-06,8.1496595813275992e-06,8.729981390136949e-06,8.7108098049626429e-06,8.2235855742009373e-06,7.5362242439236148e-06,6.7653659522616796e-06,5.8393641163207132e-06,4.7029054078221557e-06,3.4557258737704696e-06,2.2900575210873277e-06,1.362382070900996e-06,7.2789976284007546e-07],[3.0350785703745862e-08,6.971709676222853e-08,1.480098707333667e-07,2.7907848156881569e-07,4.6523217389820452e-07,7.1397279784989832e-07,1.0644550583326793e-06,1.5668553322453026e-06,2.2259403766967342e-06,3.0040412635653528e-06,3.8910143812353499e-06,4.9243990692725156e-06,6.0969357932008617e-06,7.2364177991313153e-06,8.0383062747720115e-06,8.3031818282898158e-06,8.1120545257792075e-06,7.6857891856285122e-06,7.1102653823202101e-06,6.2926088735755411e-06,5.1678795653571205e-06,3.8520711026757327e-06,2.5775087665919627e-06,1.5419217232499608e-06,8.2488375886963378e-07],[1.4947439181177789e-08,3.5496617401022532e-08,7.7660117871613112e-08,1.5014705783990768e-07,2.5721839778588456e-07,4.108632815114349e-07,6.4742399223502214e-07,1.0118359107481395e-06,1.5180329665152597e-06,2.1508076485167871e-06,2.9159028177215313e-06,3.8556948425884337e-06,4.9748526012471235e-06,6.1314381991935365e-06,7.051947123355261e-06,7.5358134250307369e-06,7.6221123132507611e-06,7.4760263853631573e-06,7.1392484755868811e-06,6.4872127418111093e-06,5.4362751351464817e-06,4.1096599584299451e-06,2.77348410854872e-06,1.6648631212498831e-06,8.8908747455705458e-07],[6.9854292699703648e-09,1.7181647526213638e-08,3.874146519823463e-08,7.6835079717273119e-08,1.3563574089845904e-07,2.266979136453285e-07,3.7917311631334369e-07,6.2923468336917505e-07,9.9456911896245767e-07,1.4759123043151211e-06,2.0908644278391572e-06,2.8847922598203153e-06,3.8733734766791933e-06,4.9500945550049307e-06,5.8888635541963543e-06,6.5092148926109874e-06,6.8216054011585549e-06,6.936937976925365e-06,6.8488997058356876e-06,6.3971228394702156e-06,5.4725812496101161e-06,4.1947501888557906e-06,2.8522787906997916e-06,1.7148379509308842e-06,9.1172530713631364e-07],[3.0987359626484584e-09,7.9052003313147382e-09,1.83678561916225e-08,3.7394088168779135e-08,6.825360954339724e-08,1.2002355694092305e-07,2.1373574531552213e-07,3.760876567214205e-07,6.2443342132228376e-07,9.6839110711667725e-07,1.4316380035841182e-06,2.0589247091036265e-06,2.8736086511717593e-06,3.8039008626361239e-06,4.6781202212270274e-06,5.350051304317685e-06,5.8157359648042244e-06,6.1409546127504816e-06,6.2770487019634879e-06,6.0316759744192488e-06,5.2686832490427935e-06,4.0932730508622691e-06,2.8016962401091878e-06,1.6844518444630834e-06,8.8966438373783939e-07],[1.3051511582946782e-09,3.4564391828793328e-09,8.2731581055535647e-09,1.7307629180523201e-08,3.2797455423823525e-08,6.1006030165587887e-08,1.1583988416296817e-07,2.1555960359297663e-07,3.7480822976036177e-07,6.0632997182455418e-07,9.3456082860510976e-07,1.3999842365102659e-06,2.0293233184288421e-06,2.7803613568021378e-06,3.5340571735691927e-06,4.1840871151378388e-06,4.7237513771543714e-06,5.1867734342667798e-06,5.4946550989155931e-06,5.4341430929646285e-06,4.8463337342403654e-06,3.8144536811169254e-06,2.6260141803009835e-06,1.576989798604608e-06,8.2607630659323259e-07],[5.2204860601272515e-10,1.4357196734690057e-09,3.5387033413700611e-09,7.6191151834938778e-09,1.5059888957185765e-08,2.9772558723052565e-08,6.0271339685353042e-08,1.1820673081999233e-07,2.146353043389531e-07,3.6170278533872774e-07,5.80947160153384e-07,9.0605144708204525e-07,1.3631299306926873e-06,1.9320471547447368e-06,2.5383483148000023e-06,3.1136793892029135e-06,3.655811043200381e-06,4.1794643237895921e-06,4.591653066052778e-06,4.6737717126727448e-06,4.25395383951925e-06,3.3900610035027518e-06,2.3457883262419518e-06,1.4059331471624516e-06,7.2968085072143243e-07]],\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"surface\",\"showscale\":false,\"showlegend\":false,\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"xaxis\":{\"title\":\"Flipper Length\"},\"yaxis\":{\"title\":\"Body MAss\"},\"zaxis\":{\"title\":\"\"}},\"hovermode\":\"closest\",\"showlegend\":false},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"colorbar\":{\"title\":\"\",\"ticklen\":2},\"colorscale\":[[\"0\",\"rgba(68,1,84,1)\"],[\"0.0416666666666667\",\"rgba(70,19,97,1)\"],[\"0.0833333333333333\",\"rgba(72,32,111,1)\"],[\"0.125\",\"rgba(71,45,122,1)\"],[\"0.166666666666667\",\"rgba(68,58,128,1)\"],[\"0.208333333333333\",\"rgba(64,70,135,1)\"],[\"0.25\",\"rgba(60,82,138,1)\"],[\"0.291666666666667\",\"rgba(56,93,140,1)\"],[\"0.333333333333333\",\"rgba(49,104,142,1)\"],[\"0.375\",\"rgba(46,114,142,1)\"],[\"0.416666666666667\",\"rgba(42,123,142,1)\"],[\"0.458333333333333\",\"rgba(38,133,141,1)\"],[\"0.5\",\"rgba(37,144,140,1)\"],[\"0.541666666666667\",\"rgba(33,154,138,1)\"],[\"0.583333333333333\",\"rgba(39,164,133,1)\"],[\"0.625\",\"rgba(47,174,127,1)\"],[\"0.666666666666667\",\"rgba(53,183,121,1)\"],[\"0.708333333333333\",\"rgba(79,191,110,1)\"],[\"0.75\",\"rgba(98,199,98,1)\"],[\"0.791666666666667\",\"rgba(119,207,85,1)\"],[\"0.833333333333333\",\"rgba(147,214,70,1)\"],[\"0.875\",\"rgba(172,220,52,1)\"],[\"0.916666666666667\",\"rgba(199,225,42,1)\"],[\"0.958333333333333\",\"rgba(226,228,40,1)\"],[\"1\",\"rgba(253,231,37,1)\"]],\"showscale\":false,\"x\":[172,174.45833333333334,176.91666666666666,179.375,181.83333333333334,184.29166666666666,186.75,189.20833333333334,191.66666666666666,194.125,196.58333333333334,199.04166666666666,201.5,203.95833333333334,206.41666666666669,208.875,211.33333333333334,213.79166666666669,216.25,218.70833333333334,221.16666666666669,223.625,226.08333333333334,228.54166666666669,231],\"y\":[2700,2850,3000,3150,3300,3450,3600,3750,3900,4050,4200,4350,4500,4650,4800,4950,5100,5250,5400,5550,5700,5850,6000,6150,6300],\"z\":[[9.3001275924167862e-07,1.6870865703239165e-06,2.6251298434760156e-06,3.5799532157659073e-06,4.3398163810702279e-06,4.7160077026929801e-06,4.6027313880111333e-06,4.014907699678511e-06,3.1100861940930658e-06,2.1494578147287579e-06,1.3702496769536763e-06,8.6204209134446032e-07,5.6593092295469496e-07,3.7659551488753658e-07,2.3071540752796522e-07,1.1905173990009362e-07,4.9071188512829451e-08,1.5875139620175176e-08,4.1807395526537601e-09,1.0605923092147327e-09,3.4898588706295745e-10,1.5110915741552405e-10,6.7785537239312536e-11,2.7961928307829915e-11,1.021806209007994e-11],[1.2307550414665466e-06,2.2314512498464284e-06,3.4795747206341578e-06,4.7719986540930608e-06,5.8378908022984664e-06,6.4165601653892099e-06,6.338014506012077e-06,5.5949123246358107e-06,4.3921354802119588e-06,3.09193589792215e-06,2.0240157695306127e-06,1.3114013722310199e-06,8.7685153554593706e-07,5.8479119677358993e-07,3.5665792004797742e-07,1.8369748710364308e-07,7.6192966598688401e-08,2.5231683320044344e-08,7.1137905160090743e-09,2.1170219257477613e-09,8.4277512869610081e-10,4.0302156091863266e-10,1.8862209038405621e-10,8.0084718701556983e-11,3.0041438621754867e-11],[1.5518700734889793e-06,2.8160419568322001e-06,4.407323891753316e-06,6.0859538438220796e-06,7.5175266696430332e-06,8.355854873744309e-06,8.3497253061546792e-06,7.4589989209119059e-06,5.9383592727713093e-06,4.2634234735461724e-06,2.8675786655804339e-06,1.9112696247102373e-06,1.2996123502761089e-06,8.6887738175592138e-07,5.2847127821903361e-07,2.7249691448031963e-07,1.1436501648048361e-07,3.9243785453642158e-08,1.2145587071554808e-08,4.3045539972189332e-09,2.0004750669393398e-09,1.0260518269611879e-09,4.9713205355755901e-10,2.1690772879724431e-10,8.3518509906761176e-11],[1.8632769900691712e-06,3.3881129100683999e-06,5.3302296567387815e-06,7.420770930736903e-06,9.2617696482829547e-06,1.0411656977796349e-05,1.0524253238521423e-05,9.5167965519162423e-06,7.6909804044574954e-06,5.6380598857751761e-06,3.897704739384992e-06,2.6693664516264247e-06,1.8443480392539034e-06,1.2375597752407838e-06,7.5272865851087066e-07,3.9023441629965357e-07,1.6699075497024972e-07,6.0306132214917709e-08,2.0976844741347667e-08,8.8160171340972085e-09,4.605081910084963e-09,2.4850540871452963e-09,1.2408163330526222e-09,5.5579131028374078e-10,2.1967327552299284e-10],[2.128993183032315e-06,3.8835076001652754e-06,6.1504302948127201e-06,8.64482973999801e-06,1.0911210176933416e-05,1.2409358847255765e-05,1.2691010104754672e-05,1.1623331602433325e-05,9.5455471422553148e-06,7.1532795270906568e-06,5.0838019714220265e-06,3.5742492175902822e-06,2.5092446457499156e-06,1.6935057694436742e-06,1.0341274242435577e-06,5.4219292555477729e-07,2.3894411018230926e-07,9.2427319433180964e-08,3.6709444292905327e-08,1.7923344544855444e-08,1.0190620312098219e-08,5.7165388875977802e-09,2.9334556945177184e-09,1.3478946373480753e-09,5.4692293533727054e-10],[2.3135992039392184e-06,4.2378599378600022e-06,6.7663841348710874e-06,9.6155674738512113e-06,1.2285241372552454e-05,1.4142693042630431e-05,1.4640224350274947e-05,1.359159254336909e-05,1.1357046030253627e-05,8.7101985389275803e-06,6.3649325019593799e-06,4.5916525316740505e-06,3.2780248128174486e-06,2.2324800203713868e-06,1.3758677144798757e-06,7.3513981086886528e-07,3.377058030842352e-07,1.4228956519788849e-07,6.4743733432169363e-08,3.5687821988872824e-08,2.1565628832586059e-08,1.2482789431082889e-08,6.5712339446423502e-09,3.095424358539563e-09,1.2895615658199168e-09],[2.3898569074619881e-06,4.4001765760130193e-06,7.0933267260184332e-06,1.0206330111402794e-05,1.3213590301317134e-05,1.5407151100581445e-05,1.615443292941138e-05,1.5218071443260254e-05,1.2957061740925179e-05,1.0182812919881821e-05,7.6536151391275198e-06,5.6657744786680489e-06,4.1206894718670642e-06,2.8444053197762186e-06,1.7811103919724308e-06,9.7894029702988546e-07,4.7490672866206101e-07,2.2060854781289234e-07,1.1392123225999009e-07,6.8883684519548187e-08,4.3521411844657018e-08,2.5874343501582399e-08,1.3954457573443655e-08,6.734832915870016e-09,2.8808483999487131e-09],[2.3452705284907413e-06,4.344903940818449e-06,7.0825299956905258e-06,1.0333593198031505e-05,1.3570819250387716e-05,1.6039161883294486e-05,1.704785684926248e-05,1.6317258219434228e-05,1.4180016636332218e-05,1.1435768973987405e-05,8.8471244441878123e-06,6.7263262707885937e-06,4.9979230332172361e-06,3.516263667682217e-06,2.2551369418109662e-06,1.2883570104313557e-06,6.6789501248652726e-07,3.4349784797965628e-07,1.9770005070061089e-07,1.2799542126303962e-07,8.3646364919281751e-08,5.0926190398967219e-08,2.8106553311759868e-08,1.3890038660153677e-08,6.100039637689048e-09],[2.1854259239698256e-06,4.0785368698987195e-06,6.7332853369546923e-06,9.9764279877189369e-06,1.3304170048472411e-05,1.5950825478583493e-05,1.7204069988566907e-05,1.6757251179454256e-05,1.4892991035404158e-05,1.2347301463624606e-05,9.8442254574909869e-06,7.6999143666303005e-06,5.8679244372661367e-06,4.2356155396625859e-06,2.8070233676578834e-06,1.6839866462507687e-06,9.4048842473200691e-07,5.3321134576493396e-07,3.3491101799111527e-07,2.2797315147023833e-07,1.530379674297742e-07,9.522231550858498e-08,5.3725390411095442e-08,2.7169399320450727e-08,1.2246793468466623e-08],[1.9328860303617598e-06,3.6384122141923745e-06,6.0935254072791318e-06,9.1819217944629164e-06,1.2446213865336259e-05,1.5150051837069338e-05,1.6601425168004454e-05,1.648692000278122e-05,1.5021362643142177e-05,1.2831374345304503e-05,1.0562735940425936e-05,8.5221719971406874e-06,6.6929019450187741e-06,4.9925480770754197e-06,3.44899743841468e-06,2.1907952673682824e-06,1.3216821032231612e-06,8.1733331838152476e-07,5.4941055963788872e-07,3.882464927951133e-07,2.6655392146133702e-07,1.6924607008952124e-07,9.7520036455333123e-08,5.042978965194787e-08,2.3318689795906656e-08],[1.6219255955010847e-06,3.0839806961175033e-06,5.2487654984797642e-06,8.0546876962652657e-06,1.1108184791137283e-05,1.3739752130520034e-05,1.5318464651518018e-05,1.5546580989452796e-05,1.4562841554136606e-05,1.285253754929251e-05,1.0952429444010373e-05,9.1463042460634541e-06,7.442104084023314e-06,5.7778478906005437e-06,4.1917732344540905e-06,2.8328017571733522e-06,1.8410835219203454e-06,1.2254296457178865e-06,8.6786312168571439e-07,6.313991986793298e-07,4.4213774363531614e-07,2.8613245291722247e-07,1.6820220929839171e-07,8.8870080450106929e-08,4.2117836813255908e-08],[1.2908112682621832e-06,2.4834170830226662e-06,4.3029765359286668e-06,6.7338087936816538e-06,9.4559616310016466e-06,1.1896050214091727e-05,1.3517339143842551e-05,1.4058777261061276e-05,1.3585722251062007e-05,1.2429170160672151e-05,1.0999395641225828e-05,9.5451582794249984e-06,8.0897187690999741e-06,6.5766624664725208e-06,5.0355042786878813e-06,3.6235275879460027e-06,2.5205723999756452e-06,1.78260615063783e-06,1.3151185672445444e-06,9.8001454144031743e-07,6.9878405035664432e-07,4.604620913574641e-07,2.7586205454502628e-07,1.4877054855526885e-07,7.2173243678505275e-08],[9.7405165208785137e-07,1.899789873878446e-06,3.3573991342458152e-06,5.3643643719954571e-06,7.67596531838537e-06,9.8319058321626166e-06,1.1409987236663611e-05,1.2201882957765564e-05,1.2212214786945729e-05,1.1624878439974415e-05,1.0721523507738132e-05,9.7071356675628166e-06,8.6088803680415942e-06,7.3595775064885603e-06,5.9584071692941217e-06,4.5538585671332119e-06,3.3632054434396582e-06,2.5004475543472286e-06,1.907300300099668e-06,1.451605624089458e-06,1.0529568987114249e-06,7.0587687947077358e-07,4.3051857339071664e-07,2.3670397108908494e-07,1.1735243598716818e-07],[6.967855058306223e-07,1.3806651668128154e-06,2.4932756131119674e-06,4.0716301226272685e-06,5.9407123607321597e-06,7.7565775080419524e-06,9.2168606167828669e-06,1.0174433862306812e-05,1.0592441509314639e-05,1.0531968805721811e-05,1.0158467574358539e-05,9.6295193680151075e-06,8.9658543619881536e-06,8.0756084031052848e-06,6.9075680445845987e-06,5.5812437622449248e-06,4.3422902389537687e-06,3.3672348652393007e-06,2.6437135603677566e-06,2.0522302779390602e-06,1.5137534591976317e-06,1.031621389195963e-06,6.3983179037725081e-07,3.5814577669187043e-07,1.8108058846060158e-07],[4.7245131488647956e-07,9.5330380949983646e-07,1.7623161791248863e-06,2.9440782189860919e-06,4.3827069913335176e-06,5.8415894698118598e-06,7.1294079147296592e-06,8.1602503780551027e-06,8.8770568280587076e-06,9.2531073126111722e-06,9.3612419011107848e-06,9.3140594305313047e-06,9.1193186461107862e-06,8.6523503484717671e-06,7.7974190165332594e-06,6.6254349861687245e-06,5.3949446196712431e-06,4.3406057946507933e-06,3.4997073004933462e-06,2.7701791737798098e-06,2.0777073263687415e-06,1.4385612389528927e-06,9.0627550304562213e-07,5.1561248899116023e-07,2.6520769803986671e-07],[3.0362189195117252e-07,6.2544022914885101e-07,1.1856277829614183e-06,2.0276188500244774e-06,3.0815968775293167e-06,4.2005568362027608e-06,5.2850468570040296e-06,6.302883979417189e-06,7.1956084050338128e-06,7.8865748463813084e-06,8.3854909903092366e-06,8.76797504510693e-06,9.0275443725825647e-06,9.0063899124601038e-06,8.5196901069127596e-06,7.5750708805561635e-06,6.4243269958117619e-06,5.3461900841119216e-06,4.4231859810019551e-06,3.5716947628497328e-06,2.7246250768601112e-06,1.9156427544893811e-06,1.2244008096073842e-06,7.0671326255062232e-07,3.6874628760159435e-07],[1.8494371345115316e-07,3.8995451025278261e-07,7.5919228940569485e-07,1.329808839385585e-06,2.0648473286547949e-06,2.8850269740051476e-06,3.7583197361948503e-06,4.6936874458592079e-06,5.6444576879162536e-06,6.5176387165690947e-06,7.2893323114478177e-06,8.0097953669137786e-06,8.6620275761125659e-06,9.0625994793874843e-06,8.9644333114486517e-06,8.3060565090892371e-06,7.3125535093860995e-06,6.2846683546477459e-06,5.3371080975631559e-06,4.4006786637916542e-06,3.4159849377274809e-06,2.4379408778126298e-06,1.5790272036212029e-06,9.227067084454135e-07,4.8687554954869977e-07],[1.0678829061988633e-07,2.3108946987946623e-07,4.6265587185089038e-07,8.3033766157891636e-07,1.3184261043845902e-06,1.8935854653828854e-06,2.5665903380266473e-06,3.3729405442351372e-06,4.2841496191159417e-06,5.2153303038530555e-06,6.1335393179828073e-06,7.0759976795190273e-06,8.0220866874533146e-06,8.7762582729686876e-06,9.0466824629538839e-06,8.7079740089224918e-06,7.9425892642201379e-06,7.0472171452862665e-06,6.1488758561546159e-06,5.1835906193411169e-06,4.0970389933046144e-06,2.967260605827622e-06,1.9451541068673674e-06,1.1481945479597111e-06,6.106718567840748e-07],[5.8460794591845217e-08,1.3017925308063352e-07,2.6828888635408456e-07,4.9348190419339808e-07,8.0222259153579505e-07,1.1885275512285858e-06,1.6850086600767046e-06,2.339948047340856e-06,3.1433757672640817e-06,4.0321021681339948e-06,4.9806675683801057e-06,6.0234081085506764e-06,7.1435596479628303e-06,8.1496595813275992e-06,8.729981390136949e-06,8.7108098049626429e-06,8.2235855742009373e-06,7.5362242439236148e-06,6.7653659522616796e-06,5.8393641163207132e-06,4.7029054078221557e-06,3.4557258737704696e-06,2.2900575210873277e-06,1.362382070900996e-06,7.2789976284007546e-07],[3.0350785703745862e-08,6.971709676222853e-08,1.480098707333667e-07,2.7907848156881569e-07,4.6523217389820452e-07,7.1397279784989832e-07,1.0644550583326793e-06,1.5668553322453026e-06,2.2259403766967342e-06,3.0040412635653528e-06,3.8910143812353499e-06,4.9243990692725156e-06,6.0969357932008617e-06,7.2364177991313153e-06,8.0383062747720115e-06,8.3031818282898158e-06,8.1120545257792075e-06,7.6857891856285122e-06,7.1102653823202101e-06,6.2926088735755411e-06,5.1678795653571205e-06,3.8520711026757327e-06,2.5775087665919627e-06,1.5419217232499608e-06,8.2488375886963378e-07],[1.4947439181177789e-08,3.5496617401022532e-08,7.7660117871613112e-08,1.5014705783990768e-07,2.5721839778588456e-07,4.108632815114349e-07,6.4742399223502214e-07,1.0118359107481395e-06,1.5180329665152597e-06,2.1508076485167871e-06,2.9159028177215313e-06,3.8556948425884337e-06,4.9748526012471235e-06,6.1314381991935365e-06,7.051947123355261e-06,7.5358134250307369e-06,7.6221123132507611e-06,7.4760263853631573e-06,7.1392484755868811e-06,6.4872127418111093e-06,5.4362751351464817e-06,4.1096599584299451e-06,2.77348410854872e-06,1.6648631212498831e-06,8.8908747455705458e-07],[6.9854292699703648e-09,1.7181647526213638e-08,3.874146519823463e-08,7.6835079717273119e-08,1.3563574089845904e-07,2.266979136453285e-07,3.7917311631334369e-07,6.2923468336917505e-07,9.9456911896245767e-07,1.4759123043151211e-06,2.0908644278391572e-06,2.8847922598203153e-06,3.8733734766791933e-06,4.9500945550049307e-06,5.8888635541963543e-06,6.5092148926109874e-06,6.8216054011585549e-06,6.936937976925365e-06,6.8488997058356876e-06,6.3971228394702156e-06,5.4725812496101161e-06,4.1947501888557906e-06,2.8522787906997916e-06,1.7148379509308842e-06,9.1172530713631364e-07],[3.0987359626484584e-09,7.9052003313147382e-09,1.83678561916225e-08,3.7394088168779135e-08,6.825360954339724e-08,1.2002355694092305e-07,2.1373574531552213e-07,3.760876567214205e-07,6.2443342132228376e-07,9.6839110711667725e-07,1.4316380035841182e-06,2.0589247091036265e-06,2.8736086511717593e-06,3.8039008626361239e-06,4.6781202212270274e-06,5.350051304317685e-06,5.8157359648042244e-06,6.1409546127504816e-06,6.2770487019634879e-06,6.0316759744192488e-06,5.2686832490427935e-06,4.0932730508622691e-06,2.8016962401091878e-06,1.6844518444630834e-06,8.8966438373783939e-07],[1.3051511582946782e-09,3.4564391828793328e-09,8.2731581055535647e-09,1.7307629180523201e-08,3.2797455423823525e-08,6.1006030165587887e-08,1.1583988416296817e-07,2.1555960359297663e-07,3.7480822976036177e-07,6.0632997182455418e-07,9.3456082860510976e-07,1.3999842365102659e-06,2.0293233184288421e-06,2.7803613568021378e-06,3.5340571735691927e-06,4.1840871151378388e-06,4.7237513771543714e-06,5.1867734342667798e-06,5.4946550989155931e-06,5.4341430929646285e-06,4.8463337342403654e-06,3.8144536811169254e-06,2.6260141803009835e-06,1.576989798604608e-06,8.2607630659323259e-07],[5.2204860601272515e-10,1.4357196734690057e-09,3.5387033413700611e-09,7.6191151834938778e-09,1.5059888957185765e-08,2.9772558723052565e-08,6.0271339685353042e-08,1.1820673081999233e-07,2.146353043389531e-07,3.6170278533872774e-07,5.80947160153384e-07,9.0605144708204525e-07,1.3631299306926873e-06,1.9320471547447368e-06,2.5383483148000023e-06,3.1136793892029135e-06,3.655811043200381e-06,4.1794643237895921e-06,4.591653066052778e-06,4.6737717126727448e-06,4.25395383951925e-06,3.3900610035027518e-06,2.3457883262419518e-06,1.4059331471624516e-06,7.2968085072143243e-07]],\"type\":\"surface\",\"showlegend\":false,\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n### 2-Dimensional\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(penguins, aes(x = flipper_len, y = body_mass)) +\n  geom_point() +\n  stat_density_2d(aes(fill = after_stat(level))) +\n  xlim(c(170, 236)) +\n  ylim(c(2500, 6250))\n```\n\n::: {.cell-output-display}\n![](5_files/figure-revealjs/unnamed-chunk-13-1.png){width=960}\n:::\n:::\n\n\n:::\n\n## Linear Model\n\n$$\nY = \\beta_0 + \\beta_1 X + \\varepsilon\n$$\n\n$$\n\\varepsilon \\sim DGP_3\n$$\n\n## Scatter Plot\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(penguins, aes(flipper_len, body_mass)) + \n  geom_point() \n```\n\n::: {.cell-output-display}\n![](5_files/figure-revealjs/unnamed-chunk-14-1.png){width=960}\n:::\n:::\n\n\n## Imposing a Line\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(penguins, aes(flipper_len, body_mass)) + \n  geom_point() +\n  stat_smooth(method = \"lm\", se = F) \n```\n\n::: {.cell-output-display}\n![](5_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n\n## Modelling the Data\n\n$$\nY_i = \\beta_0 + \\beta_1 X_i + \\varepsilon_i\n$$\n\n## Linear Model\n\n$$\n\\hat Y_i = \\hat \\beta_0 + \\hat \\beta_1 X_i\n$$\n\n::: fragment\nGoal is to obtain numerical values for $\\hat \\beta_0$ and $\\hat \\beta_1$ that will minimize the SSE.\n:::\n\n## SSE\n\n$$\n\\sum^n_{i=1} (Y_i-\\hat Y_i)^2\n$$\n\n\n$$\n\\hat Y_i = \\hat \\beta_0 + \\hat \\beta_1 X_i\n$$\n\n## Fitting a Model in R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nxlm <- lm(Y ~ X, data = DATA)\nxlm\n```\n:::\n\n\n- `X`: Name Predictor Variable of Interest in data frame `DATA`\n- `Y`: Name Outcome Variable of Interest in data frame `DATA`\n- `DATA`: Name of the data frame\n\n## Example\n\n\nY: `body_mass`; X: `flipper_len`\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nxlm <- lm(body_mass ~ flipper_len, data = penguins)\nxlm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> lm(formula = body_mass ~ flipper_len, data = penguins)\n#> \n#> Coefficients:\n#> (Intercept)  flipper_len  \n#>    -5872.09        50.15\n```\n\n\n:::\n:::\n\n\n\n$$\n\\hat Y_i = -5872.09 + 50.15 X_i\n$$\n\n\n## Interpretation of $\\hat\\beta_0$\n\nThe intercept $\\hat \\beta_0$ can be interpreted as the base value when $X$ is set to 0.\n\n::: fragment\nSome times the intercept can be interpretable to real world scenarios.\n:::\n\n::: fragment\nOther times it cannot.\n:::\n\n## Interpreting Example\n\n$$\n\\hat Y_i = -5872.09 + 50.15 X_i\n$$\n\nWhen flipper length is 0 mm, the body mass is -5872 grams.\n\n## Interpretation of $\\hat \\beta_1$\n\nThe slope $\\hat \\beta_1$ indicates how will y change when x increases by 1 unit.\n\n::: fragment\nIt will demonstrate if there is, on average, a positive or negative relationship based on the sign provided.\n:::\n\n## Interpreting Example\n\n$$\n\\hat Y_i = -5872.09 + 50.15 X_i\n$$\n\nWhen flipper length increases by 1 mm, the body mass will increase by 50.15 grams.\n\n\n# Prediction\n\n## Statistical Model\n\n$$\n\\hat Y = \\hat \\beta_0 + \\hat \\beta_1 X\n$$\n\n- $X$: Input\n- $\\hat Y$: Output\n\n## Prediction\n\nUsing the equation $\\hat Y$, we can give it a value of $X$ and then, in return, a value of $\\hat Y$ that predicts the true value $Y$.\n\n## Prediction in R\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nxlm <- lm(Y ~ X,\n            data = DATA)\n\npredict_df <- data.frame(X = VAL)\n\npredict(xlm,\n        predict_df)\n```\n:::\n\n\n- `X`: Name Predictor Variable of Interest in data frame `DATA`\n- `Y`: Name Outcome Variable of Interest in data frame `DATA`\n- `DATA`: Name of the data frame\n- `VAL`: Value for the Predictor Variable\n\n\n## Example 1\n\n::: panel-tabset\n\n### Example\n\nPredict the body mass for a penguin with a flipper length of 185.\n\n### Code\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nxlm <- lm(body_mass ~ flipper_len,\n            data = penguins)\n\nxlm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> lm(formula = body_mass ~ flipper_len, data = penguins)\n#> \n#> Coefficients:\n#> (Intercept)  flipper_len  \n#>    -5872.09        50.15\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\npredict_df <- data.frame(flipper_len = 185)\n\npredict(xlm,\n        predict_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>        1 \n#> 3406.262\n```\n\n\n:::\n:::\n\n\n:::\n\n## Example 2\n\n\n::: panel-tabset\n\n### Example\n\nPredict the body mass for a penguin with a flipper length of 205.\n\n### Code\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nxlm <- lm(body_mass ~ flipper_len,\n            data = penguins)\n\n\nxlm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> lm(formula = body_mass ~ flipper_len, data = penguins)\n#> \n#> Coefficients:\n#> (Intercept)  flipper_len  \n#>    -5872.09        50.15\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\npredict_df <- data.frame(flipper_len = 190)\n\npredict(xlm,\n        predict_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>        1 \n#> 3657.028\n```\n\n\n:::\n:::\n\n\n:::\n\n## Interpolation\n\nInterpolation is the process of estimating a value within the range of the observed input data $X$. \n\n## Extrapolation\n\nExtrapolation is the process of estimating a value beyond the range of observed input data $X$. It's about venturing into the unknown, using what we know as a guide.\n\n## Extrapolation\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(penguins, aes(flipper_len, body_mass)) + \n  xlim(160, 250) +\n  ylim(2600, 7000) +\n  geom_point() +\n  stat_smooth(method = \"lm\", se = F) \n```\n\n::: {.cell-output-display}\n![](5_files/figure-revealjs/unnamed-chunk-21-1.png){width=960}\n:::\n:::\n\n\n\n\n",
    "supporting": [
      "5_files/figure-revealjs"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../site_libs/plotly-binding-4.12.0/plotly.js\"></script>\n<script src=\"../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/plotly-main-2.25.2/plotly-latest.min.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}